/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gadgetstore;

import gadgetstore.classes.Catalogue;
import gadgetstore.classes.DBHelper;
import gadgetstore.classes.FileHelper;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.GridLayout;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author SAM
 */
public class HomePage extends javax.swing.JFrame {
    String cartPath = "cart.txt";
    Double total = 0.0;
    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
        
        FileHelper.CreateFile(this.cartPath);
        
        DBHelper db = new DBHelper();
            
        ResultSet set = db.ExecuteQuery("SELECT * FROM catalogue LIMIT 30");

        this.GenerateItem(set, true, null, false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabelFinalPrice = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jCheckBoxLaptop = new javax.swing.JCheckBox();
        jCheckBoxTablet = new javax.swing.JCheckBox();
        jLabel13 = new javax.swing.JLabel();
        jComboBoxRAM = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jComboBoxStorageSize = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldMinCost = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jTextFieldMaxCost = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jComboBoxBrandName = new javax.swing.JComboBox();
        jLabel21 = new javax.swing.JLabel();
        jComboBoxScreenSize = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();

        jToggleButton1.setText("jToggleButton1");

        jLabel10.setText("jLabel10");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jTextField1.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jTextField1.setText("Search...");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gadgetstore/images/pay.png"))); // NOI18N
        jLabel18.setText("SAPERSTEIN");

        jLabel19.setBackground(new java.awt.Color(204, 0, 51));
        jLabel19.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("  Store");
        jLabel19.setOpaque(true);

        jButton2.setBackground(new java.awt.Color(255, 204, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gadgetstore/Shopping Cart Loaded.png"))); // NOI18N
        jButton2.setText("Checkout");
        jButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(204, 204, 204));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gadgetstore/Search_24px.png"))); // NOI18N
        jButton3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabelFinalPrice.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabelFinalPrice.setForeground(new java.awt.Color(255, 255, 255));

        jButton4.setBackground(new java.awt.Color(255, 204, 0));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gadgetstore/Contacts.png"))); // NOI18N
        jButton4.setText("Sign in");
        jButton4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 204, 0));
        jButton5.setText("Payment");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabelFinalPrice)
                        .addGap(152, 152, 152))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19))
                                .addGap(8, 8, 8))
                            .addComponent(jLabelFinalPrice))
                        .addGap(11, 11, 11))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                            .addComponent(jTextField1)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                        .addGap(19, 19, 19))))
        );

        jPanel4.setBackground(new java.awt.Color(204, 0, 51));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel12.setText("DEVICE TYPE");

        jCheckBoxLaptop.setBackground(new java.awt.Color(204, 0, 51));
        jCheckBoxLaptop.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxLaptop.setText("Laptop");

        jCheckBoxTablet.setBackground(new java.awt.Color(204, 0, 51));
        jCheckBoxTablet.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxTablet.setText("Tablet");

        jLabel13.setBackground(new java.awt.Color(0, 0, 0));
        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel13.setText("RAM");

        jComboBoxRAM.setBackground(new java.awt.Color(204, 0, 51));
        jComboBoxRAM.setEditable(true);
        jComboBoxRAM.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jComboBoxRAM.setForeground(new java.awt.Color(255, 255, 255));
        jComboBoxRAM.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--- NONE ---", "1GB", "2GB", "3GB", "4GB", "5GB", "6GB", "7GB", "8GB", "16GB", "32GB" }));
        jComboBoxRAM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxRAMActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("STORAGE SIZE");

        jLabel15.setBackground(new java.awt.Color(0, 0, 0));
        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("COST");

        jComboBoxStorageSize.setBackground(new java.awt.Color(204, 0, 51));
        jComboBoxStorageSize.setEditable(true);
        jComboBoxStorageSize.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jComboBoxStorageSize.setForeground(new java.awt.Color(255, 255, 255));
        jComboBoxStorageSize.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--- NONE ---", "30 GB", "50 GB", "150 GB", "200 GB", "250 GB", "300 GB", "350 GB", "500 GB", "750 GB", "1 TB" }));

        jLabel16.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("MIN:");

        jTextFieldMinCost.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        jButton1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gadgetstore/Search_24px.png"))); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("MAX:");

        jTextFieldMaxCost.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        jLabel20.setBackground(new java.awt.Color(0, 0, 0));
        jLabel20.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel20.setText("BRAND");

        jComboBoxBrandName.setBackground(new java.awt.Color(204, 0, 51));
        jComboBoxBrandName.setEditable(true);
        jComboBoxBrandName.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jComboBoxBrandName.setForeground(new java.awt.Color(255, 255, 255));
        jComboBoxBrandName.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--- NONE ---", "ACER", "ASUS", "DELL", "HP", "LENOVO", "SAMSUNG", "SHARP", "SONY", "TECHNO" }));
        jComboBoxBrandName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxBrandNameActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setText("SCREEN SIZE");

        jComboBoxScreenSize.setBackground(new java.awt.Color(204, 0, 51));
        jComboBoxScreenSize.setEditable(true);
        jComboBoxScreenSize.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jComboBoxScreenSize.setForeground(new java.awt.Color(255, 255, 255));
        jComboBoxScreenSize.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--- NONE ---", "6 '", "7 '", "8 '", "9 '", "10 '", "11 '", "12 '", "13 '", "14 '", "15 '", "16 '", "17 '", " " }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxTablet)
                            .addComponent(jLabel12)
                            .addComponent(jCheckBoxLaptop))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel20)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jComboBoxRAM, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jComboBoxStorageSize, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jComboBoxScreenSize, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jComboBoxBrandName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jTextFieldMaxCost, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                            .addComponent(jLabel16)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTextFieldMinCost, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 22, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(jCheckBoxLaptop)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxTablet)
                .addGap(28, 28, 28)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxBrandName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxRAM, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxStorageSize, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxScreenSize, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jTextFieldMinCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jTextFieldMaxCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel3.setAutoscrolls(true);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1125, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jComboBoxRAMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxRAMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxRAMActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        this.jButton2.setVisible(true);
        String[] ids = null;
        try
        {
            //get value preference
            String deviceType, brandName;
            double ramSize, storageSize, screenSize, minCost, maxCost;

            deviceType = (jCheckBoxLaptop.isSelected()) ? "Laptop" : "Tablet";
            
            brandName = ((!jComboBoxBrandName.getSelectedItem().toString().equals("--- NONE ---")) ?
                        jComboBoxBrandName.getSelectedItem().toString().trim() : 
                        "");
            
            ramSize = ((!jComboBoxRAM.getSelectedItem().toString().equals("--- NONE ---")) ?
                        Double.parseDouble(jComboBoxRAM.getSelectedItem().toString().replace("GB", "").trim()) : 
                        0.0);
            
            if(!jComboBoxStorageSize.getSelectedItem().toString().toLowerCase().equals("--- none ---"))
            {
                String text = jComboBoxStorageSize.getSelectedItem().toString().toLowerCase();
                
                if(text.contains("tb"))
                {
                    double value = Double.parseDouble(
                            text.replace("tb", "").trim()
                    );
                    value *= 1024.00;
                    
                    storageSize = value;
                }
                else
                {
                    double value = Double.parseDouble(
                            text.replace(" gb", "").trim()
                    );
                    
                    
                    value *= 1024.00;
                    
                    storageSize = value;
                }
            }
            else
                storageSize = 0.0;
            
            
            screenSize = ((!jComboBoxScreenSize.getSelectedItem().toString().equals("--- NONE ---")) ?
                        Double.parseDouble(jComboBoxScreenSize.getSelectedItem().toString().replace("'", "").trim()) : 
                        0.0);
            
            
            minCost = (!jTextFieldMinCost.getText().equals("")) ? Integer.parseInt(jTextFieldMinCost.getText().trim()) : 0.0;
            maxCost = (!jTextFieldMaxCost.getText().equals("")) ? Integer.parseInt(jTextFieldMaxCost.getText().trim()) : 0.0;
            
            Catalogue catalogue = new Catalogue();
            ids = catalogue.GetMatchedItemsId(deviceType, brandName, ramSize, storageSize, screenSize, minCost);
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Invalid min or maximum Cost input", "Invalid Inputs", JOptionPane.ERROR_MESSAGE);
        }
        
        if(ids != null)
        {
            DBHelper db = new DBHelper();
            
            ResultSet set = db.ExecuteQuery(DBHelper.GenertatQueryStringFromID(ids));
            
            this.GenerateItem(set, true, null, true);
        }
        
//        DBHelper db = new DBHelper();
//        
//        String query = "SELECT * FROM catalogue";
//        ResultSet set = null;
//        
//        try
//        {
//        
//            Connection con = ((Connection) DriverManager.getConnection("jdbc:mysql://localhost/sarpestein_db", "root", ""));
//            Statement st = (Statement) con.createStatement();
//            set = st.executeQuery(query);
//        }
//        catch(Exception ex)
//        {
//            ex.printStackTrace();
//        }
//        this.GenerateItem(set);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBoxBrandNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxBrandNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxBrandNameActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        String ids[];
        
        jButton2.setVisible(false);
        
        try
        {
            String[] lines = FileHelper.ReadData(this.cartPath);
            
            int count = 0;
            String idsConcat = "";
            String quantity = "";
            String[] qntyArray;
            
            for (String line : lines)
            {
                if (!line.equals(""))
                {
                    total += Double.parseDouble(line.trim().split(";")[2].split(":")[1].trim());
                    
                    quantity += line.trim().split(";")[1].split(":")[1].trim() + ";";
                    idsConcat += line.trim().split(";")[0].split(":")[1].trim() + ";";
                    
                    count++;
                }
            }
            
            ids = idsConcat.split(";");
            qntyArray = quantity.split(";");
            
            
            String query = DBHelper.GenertatQueryStringFromID(ids);
            System.out.println(query);
            DBHelper db = new DBHelper();
            ResultSet set = db.ExecuteQuery(query);
            
            this.GenerateItem(set, false, qntyArray, false);
            
            jLabelFinalPrice.setText("N " + total);
            System.out.println("TOTAL " + total);
            
            
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Failed to checkout. Please try again.","Checkout failed", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        steps set = new steps();
        set.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed
    
    public Double total()
    {
        Double Total=0.00;
        total = Total;
        return Total;
    }
    public void GenerateItem(ResultSet set, Boolean hideHideCartBtn, String[] quantities, Boolean searching)
    {
        ResultSet tempSet = set;
        
        int nofRows = DBHelper.CountItems(set);
        
        int noOfItemRows = ( ((nofRows % 4) == 0) ? (nofRows / 4) : (int)(Math.ceil((nofRows / 4) + 1)));
        
        jPanel3.removeAll();
        jPanel3.setLayout(null);
        
        if(searching)
            jPanel3.setLayout(new GridLayout(3 , 4, 4, 4));
        else
            jPanel3.setLayout(new GridLayout( (int)(Math.ceil((nofRows / 4) + 1)), 4, 4, 4));
        
        int counter = 0;
        int quantityCount = 0;
        try
        {
            while(set.next())
            {
                if(!searching)
                    if (counter++ == 10) break;
                else
                    if (counter++ == 30) break;
                
                DisplayItems item = new DisplayItems();

                item.setBackground(Color.WHITE);
                item.setSize(256, 350);
                
                if(!(quantities == null))
                {
                    if(!quantities[counter].equals(""))
                        item.SetQuantity(Integer.parseInt(quantities[counter].trim()));
                }

                item.SetAtToCartBtnVisibile(hideHideCartBtn);
                item.setVisible(true);
                item.doLayout();

                jPanel3.add(item, 0, 0);
                item.repaint();
                
                String basePath = "C:/Users/Programming/Pictures/PROJECT IMAGES/GadgetStore/src/gadgetstore/cart images";
                
                if (set.getString("type").toLowerCase().equals("laptop"))
                {
                    item.SetValues(
                            set.getString("id"), 
                            set.getString("brandName"), 
                            set.getString("ram") + "GB",
                            set.getString("storageSize") + "GB", set.getString("screenSize") + " inches",
                            set.getString("supplier"),
                            basePath + "/laptops/" + set.getString("picturePath"),
                            "N " + set.getString("cost").trim(),
                            this.cartPath
                    );
                }
                else
                {
                    item.SetValues(
                            set.getString("id"),
                            set.getString("brandName"), set.getString("ram"),
                            set.getString("storageSize"), set.getString("screenSize"),
                            set.getString("supplier"),
                            basePath + "/tabs/" + set.getString("picturePath"),
                            "N " + set.getString("cost").trim(),
                            this.cartPath);
                }
            }
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        
        
        jPanel3.repaint();
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JCheckBox jCheckBoxLaptop;
    private javax.swing.JCheckBox jCheckBoxTablet;
    private javax.swing.JComboBox jComboBoxBrandName;
    private javax.swing.JComboBox jComboBoxRAM;
    private javax.swing.JComboBox jComboBoxScreenSize;
    private javax.swing.JComboBox jComboBoxStorageSize;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabelFinalPrice;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldMaxCost;
    private javax.swing.JTextField jTextFieldMinCost;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
